services:
  - type: web
    name: swedish-business-scraper
    env: python
    plan: starter
    buildCommand: |
      chmod +x deploy.sh
      ./deploy.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
